# Generated by Django 2.1.4 on 2018-12-08 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='Name of a site')),
                ('site_url', models.CharField(max_length=120, verbose_name="Site's url")),
                ('account_name', models.CharField(max_length=120, verbose_name='Name of your account')),
                ('account_password', models.CharField(max_length=150, verbose_name='Password to your account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
